%YAML:1.0
---
MIN_CONTOUR_AREA: 2800
MAX_CONTOUR_AREA: 4200
MIN_ARMOR_AREA: 800
MAX_ARMOR_AREA: 1200
MIN_BOUNDING_BOX_AREA: 5000
MIN_R_BOUNDING_BOX_AREA: 380
MAX_R_BOUNDING_BOX_AREA: 540
SPLIT_GRAY_THRESH: 65
MIN_ARMOR_WH_RATIO: 5.2000000000000004e-01
MAX_ARMOR_WH_RATIO: 6.4000000000000000e-01
MIN_BOUNDING_BOX_WH_RATIO: 4.6000000000000002e-01
MAX_BOUNDING_BOX_WH_RATIO: 5.4000000000000004e-01
MAX_ENCIRCLE_R_RECT_WH_DEVIATION: 5
