%YAML:1.0
---
A0: 0      # 字母越多弹速越高
B0: 0
C0: 0
D0: 0

A1: 0
B1: 0
C1: 0
D1: 0

AA0: 0
BB0: 0
CC0: 0
DD0: 0

AA1: 0
BB1: 0
CC1: 0
DD1: 0

AAA0: 0
BBB0: 0
CCC0: 0
DDD0: 0

AAA1: 0
BBB1: 0
CCC1: 0
DDD1: 0
