%YAML:1.0
---

# PnP map to real horizontal distance for armors, m->m.
# f(x) = a + bx + cx^2 + dx^3
PNP_MAP:
  SMALL_ARMOR:
    A: -0.209
    B: 1.281
    C: -0.09129
    D: 0.007428

  BIG_ARMOR:
    A: 0.04253
    B: 0.9515
    C: 0.039
    D: -0.006053

# Offset function to hit ground targets, rad->m.
# f(x) = a + bx + cx^2 + dx^3
GND_TGT_OFFSET:
  A: -0.000326573
  B: 0.00569623
  C: 0.000029529
  D: 0.00000244395

# Current latitude, DEG.
L: 31
# Current air pressure (hPa).
P: 997
# Current air temperature (C)
T: 30

# Bullet type, must exist in bullet-data.yaml.
BULLET_TYPE: "SMALL_BULLET"
