%YAML:1.0
---
ALL_CAMS_CONFIG_FILE: "../config/all-cams-config.yaml"
ALL_LENS_CONFIG_FILE: "../config/all-lens-config.yaml"

#CAMERA: "HV_00E56446766"
#CAMERA: "DH_KE0210010102"
#CAMERA: "HV_00E98431546"
#CAMERA: "DH_KE0210010102"
CAMERA: "DH_KE0210010101"
#CAMERA: "HV_00D27551311"
#CAMERA: "HV_00E98431546"
