%YAML:1.0
---
RM_CAM_TO_IMU_DATA: !!opencv-matrix # TODO checkout this
  rows: 3
  cols: 3
  dt: d
  data: [ 0.9978, 0, -0.06595,
          0, 1, 0,
          0.06595, 0, 0.9978 ]
TM_CAM_TO_IMU_DATA: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ 0,
          -0.06,
          0 ]
#  data: [ 0.008,
#          -0.115,
#          -0.014]