%YAML:1.0
---
# param in SJTU
P_XZ_NOISE: 0.1
P_Y_NOISE: 0.1
P_X_SPEED_NOISE: 100
P_Y_SPEED_NOISE: 100
P_X_ACCELERATION_NOISE: 0
P_Y_ACCELERATION_NOISE: 0
M_X_NOISE: 1
M_Y_NOISE: 1
M_Z_NOISE: 800.
SHOOT_DELAY: 1.6550000000000001e-01
