%YAML:1.0
---
MIN_CONTOUR_AREA: 2800
MAX_CONTOUR_AREA: 4200
MIN_ARMOR_AREA: 600
MAX_ARMOR_AREA: 1200
MIN_R_BOUNDING_BOX_AREA: 280
MAX_R_BOUNDING_BOX_AREA: 680
SPLIT_GRAY_THRESH: 140
MIN_ARMOR_WH_RATIO: 4.3350000000000000e-01
MAX_ARMOR_WH_RATIO: 5.7420000000000002e-01
MIN_BOUNDING_BOX_AREA: 5000
MIN_BOUNDING_BOX_WH_RATIO: 4.1599999999999998e-01
MAX_BOUNDING_BOX_WH_RATIO: 5.8079999999999998e-01
MAX_ENCIRCLE_R_RECT_WH_DEVIATION: 5
KERNEL_SIZE: 2
DELTA_U: 50
DELTA_V: 50