%YAML:1.0
---
SPLIT_GRAY_THRESH: 65
CHANNEL_B_LOW_THRESH: 0
CHANNEL_G_LOW_THRESH: 50
CHANNEL_R_LOW_THRESH: 50
CHANNEL_B_HIGH_THRESH: 10
CHANNEL_G_HIGH_THRESH: 255
CHANNEL_R_HIGH_THRESH: 255
MIN_BOUNDING_BOX_AREA: 5000
MIN_CONTOUR_AREA: 3000
MAX_CONTOUR_AREA: 5000
MIN_ARMOR_AREA: 400
MAX_ARMOR_AREA: 1000
MIN_R_BOUNDING_BOX_AREA: 200
MAX_R_BOUNDING_BOX_AREA: 400
MIN_ARMOR_WH_RATIO: 4.5000000000000002e-01
MAX_ARMOR_WH_RATIO: 6.5000000000000001e-01
MIN_BOUNDING_BOX_WH_RATIO: 4.0000000000000002e-01
MAX_BOUNDING_BOX_WH_RATIO: 5.5000000000000004e-01
MAX_ENCIRCLE_R_RECT_WH_DEVIATION: 5
