%YAML:1.0
---
RM_CAM_TO_IMU_DATA: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1, 0, 0,
          0, 1, 0,
          0, 0, 1]
TM_CAM_TO_IMU_DATA: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ 0,        # TODO checkout this 左右
          0,        #高低
          0 ]       #前后